export default
	{
		// DV:
		"SEREBRIAKOV": 1,
		"ELENA_ANDREEVNA": 2,
		"SONYA": 3,
		"VOINITSKAJA": 4,
		"VOINITSKIJ": 5,
		"ASTROV": 6,
		"TELEGIN": 7,
		"MARINA": 8,
		"RABOTNIK": 9,
		"STOROZH": 10,

		// authors:
		"CHEHOV": 11,

		"STANISLAVSKIJ": 12,
		"CHUKOVSKIJ": 13,
		"BUNIN": 14,
		"KOROLENKO": 15,
		"BRAT_CHEHOVA": 16,
		"ZHENA_CHEHOVA": 17,
		"GORKIJ": 18,
		//
		"UCHITEL": 19,
		"JA": 20,


		// VS:
		"RANEVSKAJA": 21,
		"ANJA": 22,
		"VARJA": 23,
		"GAEV": 24,
		"LOPAHIN": 25,
		"TROFIMOV": 26,
		"SIMEONOV": 27,
		"SHARLOTTA": 28,
		"EPIHODOV": 29,
		"DUNYASHA": 30,
		"FIRS": 31,
		"YASHA": 32,
		"PROHOZHIJ": 33,
		"NACHALNIK_STANCII": 34,
		"POCHTOVYJ_CHINOVNIK": 35,
		"GOSTI_PRISLUGA": 36,

		//

		"SILUET": 40,

	}
